### ISSUE TITLE
No Response From Server

### ISSUE THREAD

**Issue by khansaad1275** [lukeaschenbrenner/TxtNet-Browser#2]
I am trying to use this application in my phone, but it is not anything beside showing my the home page. here is some information about my phone.

Phone :  Google pixel 4XL
Android version : 13
My location: Mumbai - India

Tried with internet as well as without internet.

**Comment by PhilMinecraft** [comment]
Same on my Infinix Zero 5G ;-;
Also, first time user here

**Comment by dad1nh0** [comment]
Same here on my S22 Ultra, when I select on of the links recommended it keeps showing "loading" forever

**Comment by legendsayantan** [comment]
Does it show any error messages? I think a common cause for this problem is your sim company not allowing international sms (or maybe because you don't have a roaming plan)...

**Comment by dad1nh0** [comment]
Maybe it's related to the dual Sim? Because I have a roaming plan and AFAIK my sim company allow international SMS. Ive just updated the app and still only shows "loading" when I try any website

**Comment by lukeaschenbrenner** [comment]
Thank you everyone for the issue reports. The current reason why web requests may be stuck at "Loading..." is likely because the server cannot communicate with Twilio's API. I am working on improving the reliability of the server's uptime. Occasionally, the server will disconnect from the internet, which causes all requests to be dropped. I am working to move the server to a dedicated VPS provider and will provide updates ASAP. As far as dual-sim support goes, I will be working to add that shortly as well.
Most international numbers are not able to send text messages to the toll-free Twilio number I am using. I am also working on allowing international numbers to receive/send text messages so that they can use this app. As always, anyone is able to self-host the server in their own country and use an SMS API number that is local to them, which will solve this issue.

As of right now, I can verify that the server is up!

**Comment by Sypirious** [comment]
I have the same issue on my phone. The server does receive my messages correctly and even responds to my stop/unstop requests but anything other than that and its radio silence.

**Comment by fierytechknowhows** [comment]
I am having problems too. I am able to use both stop and unstop in the Samsung messages app and txtnet browser and I get a response back from the server. But when I try to go to any website it just says loading and gives an SMS generic failure. Im wondering if anyone else is having this same "SMS generic failure" message since I haven't seen it anywhere else on here.

**Comment by PhilMinecraft** [comment]
> 

Oh, do I need my SIM should support international messages, that's a bummer, I don't like my country lololol

**Comment by Prawnrod** [comment]
I am having this exact issue is there a fix yet?

**Comment by lukeaschenbrenner** [comment]
@Prawnrod Hi, thanks for your interest. I am still in active development on integrating the server and client into one app to allow for a low barrier to entry, low cost, distributed model. I already completed the foundational work so I am now integrating all of the encoding, web parsing, and SMS handling pieces together. I'm aiming for a functional alpha release sometime in March.

**Comment by lukeaschenbrenner** [comment]
Hello everyone, I just wanted to give you all an update that TxtNet Browser has been updated to allow for anyone to host their own server using an Android phone connected to Wi-Fi/data with an unlimited SMS plan. This allows for users from other, non +1 country code countries to also use TxtNet Browser as long as a server host is available for that country code.

In addition, I will soon be providing a server host from a +1 country code number that supports international SMS to the following countries:
- American Samoa
- Andorra
- Argentina
- Australia
- Bangladesh
- Bermuda
- Bhutan
- Brazil
- Brunei
- Cambodia
- Canada
- Cayman 
- Chile
- China
- Colombia
- Costa Rica
- Croatia
- Cyprus
- Czech Republic
- Denmark
- Dominican 
- Faroe Islands
- France
- French Guiana
- Germany
- Guadeloupe
- Guam
- Hong Kong
- Hungary
- Iceland
- India
- Indonesia
- Ireland
- Israel
- Japan
- Kazakhstan
- Kuwait
- Laos
- Luxembourg
- Macao
- Malaysia
- Malta
- Mariana Islands
- Martinique
- Mauritius
- Mayotte Island
- Mexico
- Mongolia
- Namibia
- Nepal 
- New Zealand
- Norway
- Pakistan
- Paraguay
- Peru
- Puerto Rico
- Reunion Island
- Romania
- San Marino
- Saudi 
- Singapore
- Slovakia
- South Korea
- Spain
- Sweden
- Taiwan
- Thailand
- United Kingdom
- Uruguay
- US Virgin Islands
- Vietnam

**If your phone plan does not charge extra for international SMS to a +1 number**, then you won't even need to have a second phone to setup server hosting yourself!

**Comment by RainbowShatter** [comment]
what happens if i try to connect with +55 into your +1?
