### ISSUE TITLE
Loaded page isn't displayed.

### ISSUE THREAD

**Issue by flitzekex** [lukeaschenbrenner/TxtNet-Browser#20]
When I try to load any page, it does display as loading, and all SMS messages are properly sent, but the page doesn't display. It just stops loading.
I am using the self hosting.

**Comment by lukeaschenbrenner** [comment]
Can you provide a log of the content of the SMS messages sent/received during the request?

**Comment by flitzekex** [comment]
![Screenshot_20230706_190813_Messages](https://github.com/lukeaschenbrenner/TxtNet-Browser/assets/101521849/d4cf6e25-7ff1-45cf-adde-2af8d0ca4d4b)

**Comment by flitzekex** [comment]
Tried to access site: frogfind.com

**Comment by lukeaschenbrenner** [comment]
Thanks for the info. Can you please provide your mobile carrier, phone model number, and android version? It seems like your carrier is corrupting some characters in transit, and for some reason, the last message is delivered twice.

**Comment by flitzekex** [comment]
Ok.

Carrier: E-Plus/Telefonica (Germany)
Model:

Host: Samsung Galaxy S6 (SM-G920F) with Android 7
Client: Galaxy A33 (SM-A336B/DSN) with Android 13

Although while inspecting, I see that the last message is only recieved twice. The Host doesn't show that the last message was sent twice.

**Comment by flitzekex** [comment]
SMS history 
![Uploading Screenshot_20230706-212140.jpg…]()
of the host phone

**Comment by flitzekex** [comment]
SMS history of the host phone:
![Screenshot_20230706-212140](https://github.com/lukeaschenbrenner/TxtNet-Browser/assets/101521849/7cfecce4-c3f4-46bb-968c-e00f418ae4c4)

**Comment by lukeaschenbrenner** [comment]
Sorry for such a long delay. The issue here is that your carrier is one of many that does not support the full GSM-7 character set for some reason. If you look in the first server data text before "+Y" you see this character ¤ outgoing, but the carrier modifies the character mid-transmission to rx it as "o". This is entirely a fault/bug somewhere within the pipeline of the carrier, so sadly there's nothing I can do except recommend you complain to your carrier that ¤ doesn't send over GSM-7!
