### ISSUE TITLE
Server hosting using sms over email

### ISSUE THREAD

**Issue by NoSadBeHappy** [lukeaschenbrenner/TxtNet-Browser#22]
Would be a cool feature!

**Comment by NoSadBeHappy** [comment]
Another option would be to use something like google voice, I just want to be able to host a server on my computer and not have to have an android phone running a server. I am willing to help with development, but I don't really understand how it works right now, so I might not be much use.

**Comment by NoSadBeHappy** [comment]
According to this thread (https://support.google.com/voice/thread/1646686/any-api-for-google-voice-so-that-i-can-send-text-in-my-program?hl=en) , it is no longer possible, but also someone posted a link to this(https://sphinxdoc.github.io/pygooglevoice/index.html) but it is over 10 years old.
Therefor I don't think google voice would be possible. 

Email on the other hand is easier, as there are libraries. I think this server can be edited from your python version, using something like this tutorial: https://medium.com/@Tanweer_Ali/send-emails-for-free-using-gmails-api-in-python-5b56c38d9a36

**Comment by lukeaschenbrenner** [comment]
I've looked into this as a possibility before, but there are a few blocking issues with the email approach.
- Potential throughput of email is too low for this project
- Limited support for carriers, and most carriers do not support inbound SMS
- Even if a carrier does support it, they have stricter spam filters in place that would likely block the receipt of SMS after a relatively burst number of emails were sent

I can potentially see this working for a very low data, time-insensitive project, but I don't think it's suitable for TxtNet Browser. What WOULD be possible is something like hooking the Google Voice app to Android's internal SMS API's so that Google Voice can act as a regular SMS app. An Xposed module was created to do this a while back (2015?) but it hasn't been updated in a while and no longer works. If you have any ideas or comments about anything I said feel free to reply.
