### ISSUE TITLE
Server offline

### ISSUE THREAD

**Issue by itsnebulalol** [lukeaschenbrenner/TxtNet-Browser#25]
The server on the README seems to be offline. When TxtNet sends a message, there is never a response from it.

**Comment by lukeaschenbrenner** [comment]
Sorry, it seems like the app experiences a bug after a large period of time or the Android process manager keeps killing the app after some time. I haven't had the time yet to look into what the issue is with proper logging, but I will work on that over the next few weeks to pinpoint how exactly the server is getting killed every few days so that I can make the server more robust. It could be related to the WebViews getting killed even though the TxtNet service is still running, so the service is stuck forever waiting to service requests. In the meantime, however, the server is up and running atm.

**Comment by itsnebulalol** [comment]
Still doesn't seem to be replying to messages

**Comment by lukeaschenbrenner** [comment]
I can manually check message logs if you'd like to see if the message is getting sent. Just message your GitHub username over SMS to that number and reply here. Sorry for the late reply, I've been slammed with a bunch of other things lately.

**Comment by itsnebulalol** [comment]
No worries. Do you mean text my GitHub username to that phone number in the readme?

**Comment by itsnebulalol** [comment]
Not sure if my reply sent but I sent the text message, sorry about the double reply.

**Comment by silvertakana** [comment]
Does anyone have an alternative server?

**Comment by lukeaschenbrenner** [comment]
Really sorry for not getting back to you right away @itsnebulalol . I've had a lot of pressing things to take care of and haven't had proper time to commit to this project lately. Your messages were coming through and the server had been up until August 24th. However, your phone's carrier has a bug where it's corrupting certain characters sent in GSM-7 encoding ( see #3 ). Because of that, TxtNet Server messages run into an issue where they send 2 characters that get converted into one, so decoding isn't possible. There's nothing I can do on the client side besides considering a limited charset compatibility mode. If you're interested, feel free to open a new issue (though this won't be priority for a while).

**Comment by lukeaschenbrenner** [comment]
@silvertakana Someone was in talks of setting one up for the Italy region, but it looks like that fell through. Nobody else (that I know of) is hosting one publicly; sorry!

**Comment by itsnebulalol** [comment]
No worries, I traded in my Android phone anyway so i wouldn’t be able to use the app. Thanks your making a cool app though!

**Comment by lukeaschenbrenner** [comment]
Got it, sorry you weren't able to try it out but I appreciate your support!
