### ISSUE TITLE
Using the service in Iran 

### ISSUE THREAD

**Issue by bracop8** [lukeaschenbrenner/TxtNet-Browser#28]
Hi, I am not be able to use the service in Iran, May I request you that this service work in my country ?
 Thank you very much.

**Comment by lukeaschenbrenner** [comment]
Hi @bracop8 , I'd love to add a server for Iranian users, but I'm not in contact with anyone who is able to host a number with a +98 country code. Unfortunately, since I'm not being funded by anyone at the moment, I can't take requests for additional servers. If this changes in the future, I will be sure to consider the possibility!
