### ISSUE TITLE
Is the server number down

### ISSUE THREAD

**Issue by gotnamed** [lukeaschenbrenner/TxtNet-Browser#30]
Looking forward to testing your service. I'm oftentimes in an area where I can get SMS but not properly browse the internet. So I'm excited to use your product. Also I have a programming background so if you need assistance in any way please let me know I'd love to be part of this project. I can see big time benefit with this when starlink or other satellite services allow for text messaging. Basically we could still browse some websites with the sms. If you can get back to me and let me know if the number is up and running. I seem to be able to send the message to the server but nothing is received back.

Thanks again for your hard work.

Jeremy

**Comment by lukeaschenbrenner** [comment]
Hi Jeremy, thanks for the report. I'm glad to hear that this app has a use case for you! Right now due to lack of funds, the server is occasionally taken down to repurpose the Android device it is running on for other needs. In addition, one of the things I hadn't had the time to debug is the effect of a the long-running Android service being half-killed in the background, resulting in the server being unavailable. If you had the time, maybe you could compile the debug version of the app and keep a test device plugged into Android studio for some time, checking the logcat occasionally. I find that this typically occurs in under 24 hours. Right now, I verified that the server is back up and running, so please try again and report back.
