### ISSUE TITLE
Server down

### ISSUE THREAD

**Issue by peanutbutterk4** [lukeaschenbrenner/TxtNet-Browser#32]
Hi,

It seems like the server is down or my phone is not receiving messages from the server... Any updates on the status of the server?

Btw, this is an awesome project! I found this on a Google search because I was thinking something like it would be really useful!

Thanks!

**Comment by ErikUden** [comment]
It was an awesome project while it lasted!

**Comment by lukeaschenbrenner** [comment]
Hi all, sorry for such a long delay in responding to this. The app has been on hiatus since last May due to other personal commitments. However, I intend to begin picking up work again on the app very shortly. The server Android service has a recurring issue on my host phone (OnePlus 6t) where the aggressive battery optimization will kill the service without indication after some time has passed. As of writing, it is up!
