### ISSUE TITLE
Server Software for second phone

### ISSUE THREAD

**Issue by unterflieger** [lukeaschenbrenner/TxtNet-Browser#6]
Would it be possible to use a second phone __with__ active internet access as a server for the browser? This would eliminate the need to purchase a Twilio number and at the same time, make the service more reliable and, in some countries, mostly free. (Currently you would have to pay almost a dollar per SMS from Germany to America.)

**Comment by lukeaschenbrenner** [comment]
That is exactly what I am in the middle of working on! I haven't pushed any commits yet related to the feature because I am in the nitty gritty of implementing native code JNI bindings for Brotli on most architectures, but keep an eye out for updates in the very near future! Also I'm curious, how did you find this project? It seems like there has been a minor resurgence in popularity as of late.

**Comment by unterflieger** [comment]
A video about this Project went semi

**Comment by unterflieger** [comment]
@lukeaschenbrenner
A video about this project went viral on TikTok 2 Days ago (300k views) and it caught my interest, so I looked it up.

**Comment by lukeaschenbrenner** [comment]
That's a new one, thanks for letting me know. I'm glad you (and others) found it interesting! (If anyone has the link, I'd be keen to see what was covered since I haven't had the server running since November, haha.) FYI - I'll be closing this issue once I'm able to push out an initial public alpha for this feature.

**Comment by unterflieger** [comment]
The video is pretty short and doesn't contain a lot of information, but there is footage of the browser working. I don't know where they might've gotten it from though. It must've been recorded months prior.
Anyways, here's the link to the clip: https://vm.tiktok.com/ZMYFXfNxq/

**Comment by SrGato001** [comment]
Yes, I also come from that video and found this really interesting. If this gets implemented would be great as Its not possible to buy any spanish numbers from twilio, they are just unavariable. And a prepaid phone plan with sms would prob be cheaper. Sick project btw

**Comment by lukeaschenbrenner** [comment]
Hi everyone, I just wanted to let you all know that initial second phone server software support has been completed. The server will run using the phone number associated with your primary SIM. You can see [this comment](https://github.com/lukeaschenbrenner/TxtNet-Browser/issues/2#issuecomment-1510506701) for a little more information. Thanks for your interest, and let me know if you find any bugs!
